#include <Logger/Logger.h>

using namespace std;

int main(int argc, char *argv[])
{
    LOGSTART
    LOGSET(LOG_LOVEL_INFO, LOG_TARGET_FILE_AND_TERMINAL)
    INFOLOG("info")
    DEBUGLOG("debug")
    WARNINGLOG("warning")
    ERRORLOG("error")
    LOGSET(LOG_LOVEL_DEBUG, LOG_TARGET_FILE_AND_TERMINAL)
    INFOLOG("info")
    DEBUGLOG("debug")
    WARNINGLOG("warning")
    ERRORLOG("error")
    LOGSET(LOG_LOVEL_WARNING, LOG_TARGET_FILE_AND_TERMINAL)
    INFOLOG("info")
    DEBUGLOG("debug")
    WARNINGLOG("warning")
    ERRORLOG("error")
    LOGSET(LOG_LOVEL_ERROR, LOG_TARGET_FILE_AND_TERMINAL)
    INFOLOG("info")
    DEBUGLOG("debug")
    WARNINGLOG("warning")
    ERRORLOG("error")
    LOGSET(LOG_LOVEL_INFO, LOG_TARGET_TERMINAL)
    INFOLOG("info")
    DEBUGLOG("debug")
    WARNINGLOG("warning")
    ERRORLOG("error")
    LOGSET(LOG_LOVEL_INFO, LOG_TARGET_FILE)
    INFOLOG("info_")
    DEBUGLOG("debug_")
    WARNINGLOG("warning_")
    ERRORLOG("error_")
    LOGSETF(LOG_LOVEL_INFO, LOG_TARGET_TERMINAL, "./log/test.log")
    INFOLOG("info")
    DEBUGLOG("debug")
    WARNINGLOG("warning")
    ERRORLOG("error")
    LOGSETF(LOG_LOVEL_INFO, LOG_TARGET_FILE, "./log/test.log")
    INFOLOG("info")
    DEBUGLOG("debug")
    WARNINGLOG("warning")
    ERRORLOG("error")
    LOGSETF(LOG_LOVEL_INFO, LOG_TARGET_FILE_AND_TERMINAL, "./log/test.log")
    INFOLOG("info___")
    DEBUGLOG("debug___")
    WARNINGLOG("warning___")
    ERRORLOG("error___")
    LOGEND
    LOGSET(LOG_LOVEL_INFO, LOG_TARGET_FILE_AND_TERMINAL)
    INFOLOG("info")
    DEBUGLOG("debug")
    WARNINGLOG("warning")
    ERRORLOG("error")
    LOGEND
    return 0;
}